---

stages:
    - test
    - cleanup

test:
    stage: test
    script:
        - export COMPOSE_PROJECT_NAME="${CI_PIPELINE_ID}-pipes-nodejs-sdk"
        - make test

cleanup:
    stage: cleanup
    when: always
    script:
        - export COMPOSE_PROJECT_NAME="${CI_PIPELINE_ID}-pipes-nodejs-sdk"
        - make docker-down-clean